apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        -name: postgresql
        image: postgres:15.0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_BD
          valeu: "kubenews"
        - name: POSTGRES_USER
          valeu: "kubenews"
        - name: POSTGRES_PASSWORD
          valeu: "kube@news#123"
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
        -name: app
        image: fabricioveronez/kube-news:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_DATABASE
          valeu: "kubenews"
        - name: DB_USERNAME
          valeu: "kubenews"
        - name: DB_PASSWORD
          valeu: "kube@news#123"
        - name: DB_HOST
          valeu: "postgresql"
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8080
      nodePOrt: 30000
  type: NodePort